const { mongoose } = require('../config/mongo');

/**
 * Genomic Variant Schema
 * Captures structured genomic information for precision medicine
 */
const GenomicVariantSchema = new mongoose.Schema({
  gene: { type: String, required: true },           // e.g., 'EGFR', 'BRCA1', 'CYP2C19'
  variant: { type: String },                        // e.g., 'exon 19 deletion', 'L858R', '*2/*2'
  zygosity: { 
    type: String, 
    enum: ['Homozygous', 'Heterozygous', 'Hemizygous', 'Unknown'],
    default: 'Unknown'
  },
  significance: { 
    type: String, 
    default: 'Unknown'
  },
  actionability: {
    type: String,
    default: 'None'
  },
  source: { type: String },                         // e.g., 'Foundation Medicine', 'Guardant360'
  testDate: { type: Date }
}, { _id: false });

/**
 * Allergy/Adverse Reaction Schema
 * Critical for drug safety and treatment planning
 */
const AllergySchema = new mongoose.Schema({
  allergen: { type: String, required: true },       // e.g., 'Penicillin', 'Sulfa drugs', 'Contrast dye'
  allergenType: {
    type: String,
    enum: ['Drug', 'Food', 'Environmental', 'Biological', 'Other'],
    default: 'Drug'
  },
  reaction: { type: String },                       // e.g., 'Anaphylaxis', 'Rash', 'Nausea'
  severity: {
    type: String,
    enum: ['Mild', 'Moderate', 'Severe', 'Life-threatening'],
    default: 'Moderate'
  },
  onsetDate: { type: Date },
  verified: { type: Boolean, default: false }
}, { _id: false });

/**
 * Treatment Outcome Schema (embedded)
 * For tracking historical treatment responses
 */
const TreatmentOutcomeSchema = new mongoose.Schema({
  treatmentName: { type: String, required: true },
  startDate: { type: Date },
  endDate: { type: Date },
  response: {
    type: String,
    enum: ['Complete Response', 'Partial Response', 'Stable Disease', 'Progressive Disease', 'Not Evaluable'],
    default: 'Not Evaluable'
  },
  adverseEvents: [{
    event: String,
    grade: { type: Number, min: 1, max: 5 },        // CTCAE grading
    relationship: {
      type: String,
      enum: ['Definite', 'Probable', 'Possible', 'Unlikely', 'Unrelated'],
      default: 'Possible'
    }
  }],
  notes: { type: String }
}, { _id: false });

/**
 * Alert Schema (embedded)
 * For tracking clinical alerts generated by the system
 */
const AlertSchema = new mongoose.Schema({
  alertType: {
    type: String,
    enum: ['Vital', 'Lab', 'Medication', 'Deterioration', 'Interaction', 'Compliance'],
    required: true
  },
  severity: {
    type: String,
    enum: ['Info', 'Warning', 'Critical'],
    default: 'Warning'
  },
  message: { type: String, required: true },
  parameter: { type: String },                      // e.g., 'bpSystolic', 'heartRate'
  value: { type: Number },
  threshold: { type: Number },
  acknowledged: { type: Boolean, default: false },
  acknowledgedBy: { type: String },
  acknowledgedAt: { type: Date },
  createdAt: { type: Date, default: Date.now }
}, { _id: true });

const PatientSchema = new mongoose.Schema({
  patientId: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  age: { type: Number },
  gender: { type: String },
  conditions: [{ type: String }],
  profile: {
    age: Number,
    gender: String,
    height: Number,
    weight: Number,
    bmi: Number,
    bloodGroup: String,
    ethnicity: String,                              // NEW: Important for pharmacogenomics
    primaryLanguage: String                         // NEW: For patient communication
  },
  symptoms: [{ type: String }],
  medicalHistory: {
    conditions: [{ type: String }],
    surgeries: String,
    familyHistory: String,
    previousTreatments: [TreatmentOutcomeSchema]    // NEW: Historical treatment outcomes
  },
  medications: [{
    name: String,
    dosage: String,
    frequency: String,
    route: {                                        // NEW: Administration route
      type: String,
      enum: ['Oral', 'IV', 'IM', 'SC', 'Topical', 'Inhaled', 'Other'],
      default: 'Oral'
    },
    startDate: Date,                                // NEW: When medication was started
    indication: String,                             // NEW: Why prescribed
    prescriber: String                              // NEW: Who prescribed
  }],
  
  // NEW: Structured allergies section
  allergies: [AllergySchema],
  
  // ENHANCED: Structured biomarkers with genomics
  biomarkers: {
    // Legacy free-text fields (kept for backward compatibility)
    genomicVariant: String,
    therapyTarget: String,
    expressionLevel: String,
    resistanceMarker: String,
    immuneProfile: String,
    
    // NEW: Structured genomic data
    genomics: {
      variants: [GenomicVariantSchema],
      tumorMutationBurden: { type: Number },        // mutations/Mb
      microsatelliteStatus: {
        type: String,
        enum: ['MSI-H', 'MSI-L', 'MSS', 'Unknown'],
        default: 'Unknown'
      },
      pdl1Expression: { type: Number },             // TPS percentage
      herStatus: {
        type: String,
        enum: ['Positive', 'Negative', 'Equivocal', 'Unknown'],
        default: 'Unknown'
      },
      hormoneReceptorStatus: {
        er: { type: String, enum: ['Positive', 'Negative', 'Unknown'], default: 'Unknown' },
        pr: { type: String, enum: ['Positive', 'Negative', 'Unknown'], default: 'Unknown' }
      }
    },
    
    // NEW: Pharmacogenomic markers
    pharmacogenomics: {
      cyp2d6: { type: String },                     // e.g., 'Poor Metabolizer', 'Normal Metabolizer'
      cyp2c19: { type: String },
      cyp2c9: { type: String },
      cyp3a4: { type: String },
      vkorc1: { type: String },                     // Warfarin sensitivity
      tpmt: { type: String },                       // Thiopurine toxicity risk
      dpyd: { type: String },                       // 5-FU toxicity risk
      ugt1a1: { type: String }                      // Irinotecan toxicity risk
    },
    
    // NEW: Lab-based biomarkers with reference ranges
    labBiomarkers: {
      creatinine: { value: Number, unit: { type: String, default: 'mg/dL' }, date: Date },
      gfr: { value: Number, unit: { type: String, default: 'mL/min/1.73m²' }, date: Date },
      alt: { value: Number, unit: { type: String, default: 'U/L' }, date: Date },
      ast: { value: Number, unit: { type: String, default: 'U/L' }, date: Date },
      bilirubin: { value: Number, unit: { type: String, default: 'mg/dL' }, date: Date },
      albumin: { value: Number, unit: { type: String, default: 'g/dL' }, date: Date },
      hemoglobin: { value: Number, unit: { type: String, default: 'g/dL' }, date: Date },
      platelets: { value: Number, unit: { type: String, default: 'K/uL' }, date: Date },
      wbc: { value: Number, unit: { type: String, default: 'K/uL' }, date: Date },
      neutrophils: { value: Number, unit: { type: String, default: 'K/uL' }, date: Date }
    }
  },
  
  lifestyle: {
    smoking: String,
    alcohol: String,
    exercise: String,
    diet: String,
    occupation: String,                             // NEW: Occupational exposure risks
    substanceUse: String                            // NEW: Other substances
  },
  
  vitals: {
    heartRate: Number,
    bpSystolic: Number,
    bpDiastolic: Number,
    sugar: Number,
    spO2: Number,
    temperature: Number,
    respiratoryRate: Number,                        // NEW: Important for respiratory conditions
    painLevel: Number,                              // NEW: 0-10 scale
    weight: Number,                                 // NEW: Current weight (may differ from profile)
    lastUpdated: { type: Date, default: Date.now }  // NEW: Track when vitals were last taken
  },
  
  labReports: { type: mongoose.Schema.Types.Mixed },
  disease: { type: String },
  treatmentGoal: { type: String },
  
  // NEW: Clinical staging (for oncology)
  staging: {
    system: { type: String },                       // e.g., 'TNM', 'FIGO', 'Ann Arbor'
    stage: { type: String },                        // e.g., 'IIIA', 'IV'
    t: { type: String },
    n: { type: String },
    m: { type: String },
    grade: { type: String },
    dateOfDiagnosis: { type: Date }
  },
  
  // NEW: Performance status
  performanceStatus: {
    ecog: { type: Number, min: 0, max: 5 },         // ECOG scale 0-5
    karnofsky: { type: Number, min: 0, max: 100 },  // Karnofsky scale 0-100
    assessmentDate: { type: Date }
  },
  
  // NEW: Active alerts
  alerts: [AlertSchema],
  
  metrics: {
    baselineHealthIndex: Number,
    riskScore: Number,
    diseaseProbability: {
      cardiac: Number,
      respiratory: Number,
      metabolic: Number,
      oncologic: Number,                            // NEW
      neurological: Number,                         // NEW
      infectious: Number                            // NEW
    },
    // NEW: Risk scores
    riskScores: {
      cardiovascular: {                             // Framingham, ASCVD
        score: Number,
        category: String,
        calculatedAt: Date
      },
      sepsis: {                                     // qSOFA, NEWS2
        qsofa: Number,
        news2: Number,
        calculatedAt: Date
      },
      bleeding: {                                   // HAS-BLED
        score: Number,
        category: String,
        calculatedAt: Date
      },
      falls: {                                      // Morse Fall Scale
        score: Number,
        category: String,
        calculatedAt: Date
      }
    }
  },
  
  // NEW: Care team
  careTeam: [{
    role: { type: String },                         // e.g., 'Primary Oncologist', 'Nurse Navigator'
    name: { type: String },
    contactInfo: { type: String }
  }],
  
  // NEW: Insurance/administrative
  insurance: {
    provider: String,
    planType: String,
    priorAuthRequired: { type: Boolean, default: false }
  },
  
  // NEW: Patient preferences
  preferences: {
    codeStatus: { 
      type: String, 
      enum: ['Full Code', 'DNR', 'DNI', 'DNR/DNI', 'Comfort Care Only', 'Not Documented'],
      default: 'Not Documented'
    },
    advanceDirective: { type: Boolean, default: false },
    preferredContactMethod: { type: String, enum: ['Phone', 'Email', 'Portal', 'Mail'], default: 'Phone' },
    language: { type: String, default: 'English' },
    interpreterNeeded: { type: Boolean, default: false }
  },
  
  // NEW: Socio-Economic Profile for HERA (Health Economics & Resource Agent)
  socioEconomic: {
    insuranceTier: {
      type: String,
      enum: ['Uninsured', 'Medicaid', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Medicare'],
      default: 'Silver'
    },
    monthlyMedicationBudget: { type: Number, default: 150 },  // USD
    copayTolerance: {
      type: String,
      enum: ['$0-10', '$10-25', '$25-50', '$50-100', '$100+'],
      default: '$25-50'
    },
    location: {
      type: String,
      enum: ['Urban', 'Suburban', 'Rural', 'Remote'],
      default: 'Urban'
    },
    transportationAccess: {
      type: String,
      enum: ['Own Vehicle', 'Public Transit', 'Ride Share Only', 'Limited', 'None'],
      default: 'Own Vehicle'
    },
    workScheduleFlexibility: {
      type: String,
      enum: ['Flexible', 'Limited', 'Fixed Hours', 'Multiple Jobs', 'Unemployed', 'Retired'],
      default: 'Limited'
    },
    caregiverSupport: { type: Boolean, default: false },
    distanceToClinic: { type: Number, default: 10 },  // miles
    pharmacyAccess: {
      type: String,
      enum: ['Mail Order', 'Local Pharmacy', 'Hospital Only', 'Limited'],
      default: 'Local Pharmacy'
    }
  }
  
}, { timestamps: true, collection: 'patients', optimisticConcurrency: true });


// Indexes for common queries
PatientSchema.index({ 'disease': 1 });
PatientSchema.index({ 'biomarkers.genomics.variants.gene': 1 });
PatientSchema.index({ 'allergies.allergen': 1 });
PatientSchema.index({ 'alerts.severity': 1, 'alerts.acknowledged': 1 });

module.exports = mongoose.model('Patient', PatientSchema);
